### ISSUE TITLE
user: first_name + last_name validation fails. 

### ISSUE THREAD

**Issue by hannesschaletzky** [CharlesOuverleaux/rent-a-techy#25]
![image](https://user-images.githubusercontent.com/29574225/119645755-aadf7680-be1e-11eb-9990-a6d02a10aa0a.png)
![image](https://user-images.githubusercontent.com/29574225/119645801-b92d9280-be1e-11eb-93f9-d652de6bd3d3.png)

We should probably allow all characters except numbers and include dashes and spaces as well

**Comment by CharlesOuverleaux** [comment]
Done, removed charachter validation

![image](https://user-images.githubusercontent.com/33698505/119647535-ac11a300-be20-11eb-8ea5-46449cd77c19.png)
